# Generated by Django 5.0.3 on 2024-03-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_by',
            new_name='user',
        ),
    ]
